//! Regression tests for list/MAP element typing and the JSON text of scalar leaves.
//!
//! Lists and maps are JSON text here, but where a list's element type is known statically
//! (a Parquet `LIST<scalar>`/`MAP` column, `string_split`, a one-type list literal) a
//! subscript and `UNNEST` hand the element back as that type, as DuckDB does. Every expected
//! value below was checked against `duckdb` 1.4.4 (the command is in each comment).
//! `tests/data/list_scalars.parquet` is generated by `scripts/gen-testdata.sh`.

use ahiru_core::error::{code_of, Code};
use ahiru_core::format::FormatKind;
use ahiru_core::session::{Prepared, QueryStep, Session};
use ahiru_core::vector::{Field, Ty, Value};

fn data(name: &str) -> Vec<u8> {
    let p = concat!(env!("CARGO_MANIFEST_DIR"), "/../../tests/data/");
    std::fs::read(format!("{p}{name}")).unwrap_or_else(|e| panic!("{name}: {e}"))
}

fn session(file: &str) -> Session {
    let mut s = Session::new();
    s.register_bytes_as("t", data(file), FormatKind::Parquet).unwrap();
    s
}

fn run(s: &mut Session, sql: &str) -> (Vec<Field>, Vec<Vec<Value>>) {
    let mut q = match s.prepare(sql, &[]).unwrap_or_else(|e| panic!("{sql}: {e:?}")) {
        Prepared::Ready(q) => q,
        Prepared::NeedIo(_) => panic!("{sql}: unexpected NeedIo"),
    };
    let schema = q.schema.clone();
    let mut rows = Vec::new();
    loop {
        match s.step(&mut q).unwrap_or_else(|e| panic!("{sql}: {e:?}")) {
            QueryStep::Batch(mut b) => {
                b.materialize();
                for r in 0..b.num_rows() {
                    rows.push(b.cols.iter().map(|c| c.value_at(r)).collect());
                }
            }
            QueryStep::Done => break,
            QueryStep::NeedIo(_) | QueryStep::NeedCodec(_) => panic!("{sql}: unexpected I/O"),
        }
    }
    (schema, rows)
}

/// One row of `SELECT <exprs> FROM t LIMIT 1` over `basic.parquet`.
fn row(exprs: &str) -> Vec<Value> {
    let mut s = session("basic.parquet");
    run(&mut s, &format!("SELECT {exprs} FROM t LIMIT 1")).1.remove(0)
}

fn s(v: &str) -> Value {
    Value::Bytes(v.as_bytes().to_vec())
}

const NULL: Value = Value::Null;
const T: Value = Value::Bool(true);
const F: Value = Value::Bool(false);

// --- Subscripts --------------------------------------------------------------------

#[test]
fn a_null_list_element_is_sql_null() {
    // duckdb -c "select [1,NULL,3][2] IS NULL, list_extract('[1,null]'::JSON, 2) IS NULL"
    // -> true, true
    assert_eq!(
        row("[1,NULL,3][2] IS NULL, list_extract(CAST('[1,null]' AS JSON), 2) IS NULL"),
        [T, T]
    );
}

#[test]
fn count_and_max_of_a_subscript_on_a_list_column() {
    // duckdb -c "select count(xs[2]), max(xs[2]), sum(xs[-1]) from 'list_varied.parquet'"
    // -> 10, 50, 1050 (the NULL second elements are not counted)
    let mut sess = session("list_varied.parquet");
    let (schema, rows) = run(&mut sess, "SELECT count(xs[2]), max(xs[2]), sum(xs[-1]) FROM t");
    assert_eq!(schema[1].ty, Ty::BigInt);
    assert_eq!(rows, [[Value::I64(10), Value::I64(50), Value::I128(1050)]]);
}

#[test]
fn string_elements_come_back_unquoted() {
    // duckdb -c "select length(string_split('a,b', ',')[1]), string_split('a,b',',')[1] || 'x',
    // string_split('a,b',',')[2] = 'b', CAST(['a'][1] AS VARCHAR), typeof(['a'][1])"
    // -> 1, ax, true, a, VARCHAR
    assert_eq!(
        row("length(string_split('a,b', ',')[1]), string_split('a,b',',')[1] || 'x', \
             string_split('a,b',',')[2] = 'b', CAST(['a'][1] AS VARCHAR), typeof(['a'][1])"),
        [Value::I64(1), s("ax"), T, s("a"), s("VARCHAR")]
    );
}

#[test]
fn a_literal_list_element_has_the_literals_common_type() {
    // duckdb -c "select typeof([1,2][1]), [1.5, 2][2], typeof([1.5, 2][2]), [[1],[2]][2][1]"
    // -> INTEGER, 2.0, DECIMAL(11,1), 2
    let r = row("typeof([1,2][1]), CAST([1.5, 2][2] AS VARCHAR), [[1],[2]][2][1]");
    assert_eq!(r[0], s("INTEGER"));
    assert_eq!(r[1], s("2.0"));
    // An element of a nested list stays JSON text (its type is not tracked).
    assert_eq!(r[2], s("2"));
}

#[test]
fn a_list_literal_stores_its_elements_in_the_common_type() {
    // duckdb -c "select [1.5, 2], [DATE '2024-01-01', TIMESTAMP '2024-01-01 10:00'],
    // [true, 1], json_array(1.5, 2)"
    // -> [1.5, 2.0], ['2024-01-01 00:00:00', '2024-01-01 10:00:00'], [1, 1], [1.5,2]
    // The element type the list's Shape declares is also the text it holds, so the two
    // spellings of one value (`2` / `2.0`) cannot both appear in one list. `json_array`
    // is DuckDB's JSON function and keeps every argument's own type.
    assert_eq!(
        row("CAST([1.5, 2] AS VARCHAR), \
             CAST([DATE '2024-01-01', TIMESTAMP '2024-01-01 10:00'] AS VARCHAR), \
             CAST([true, 1] AS VARCHAR), CAST(json_array(1.5, 2) AS VARCHAR), \
             list_distinct([2, 2.0])"),
        [
            s("[1.5,2.0]"),
            s("[\"2024-01-01 00:00:00\",\"2024-01-01 10:00:00\"]"),
            s("[1,1]"),
            s("[1.5,2]"),
            Value::Bytes(b"[2.0]".to_vec()),
        ]
    );
}

#[test]
fn subscripts_on_typed_parquet_leaves() {
    // duckdb -c "select ds[2], ds[3], ds[4], bs[1], ss[2], ss[3], decs[1], decs[2], dates[1],
    // tss[1], flags[2], typeof(decs[1]), typeof(bs[1]) from 'list_scalars.parquet' where id = 1"
    // -> nan, inf, -inf, \x00\x01\xFF, b"c, d\e, 1.50, -0.50, 2024-01-02,
    //    2024-01-02 03:04:05.5, false, DECIMAL(4,2), BLOB
    let mut sess = session("list_scalars.parquet");
    let (schema, rows) = run(
        &mut sess,
        "SELECT ds[2], ds[3], ds[4], bs[1], ss[2], ss[3], CAST(decs[1] AS VARCHAR), \
         CAST(decs[2] AS VARCHAR), CAST(dates[1] AS VARCHAR), CAST(tss[1] AS VARCHAR), \
         flags[2] FROM t WHERE id = 1",
    );
    assert_eq!(schema[0].ty, Ty::Double);
    assert_eq!(schema[3].ty, Ty::Blob);
    let r = &rows[0];
    let Value::F64(nan) = r[0] else { panic!("{:?}", r[0]) };
    assert!(nan.is_nan());
    assert_eq!(r[1], Value::F64(f64::INFINITY));
    assert_eq!(r[2], Value::F64(f64::NEG_INFINITY));
    assert_eq!(r[3], Value::Bytes(vec![0, 1, 0xff]));
    assert_eq!(
        &r[4..],
        [
            s("b\"c"),
            s("d\\e"),
            s("1.50"),
            s("-0.50"),
            s("2024-01-02"),
            s("2024-01-02 03:04:05.5"),
            F
        ]
    );
}

#[test]
fn the_element_type_survives_a_subquery_a_cte_and_list_functions() {
    // duckdb -c "with c as (select xs as ys from 'list1.parquet') select typeof(ys[1]),
    // typeof(list_sort(ys)[1]), typeof(list_slice(ys, 1, 2)[1]) from c limit 1"
    // -> INTEGER x3
    let mut sess = session("list1.parquet");
    let (_, rows) = run(
        &mut sess,
        "WITH c AS (SELECT xs AS ys FROM t) SELECT typeof(ys[1]), typeof(list_sort(ys)[1]), \
         typeof(list_slice(ys, 1, 2)[1]), typeof(list_filter(ys, x -> true)[1]) FROM c LIMIT 1",
    );
    assert_eq!(rows[0], [s("INTEGER"), s("INTEGER"), s("INTEGER"), s("INTEGER")]);
}

// --- MAP -------------------------------------------------------------------------------

#[test]
fn map_subscript_is_a_key_lookup_returning_the_value() {
    // duckdb -c "select m['a'], m['b'], m['c'], m['z'], typeof(m['b']), map_extract(m, 'b'),
    // map_extract(m, 'z') from 'map_basic.parquet' where id = 3"
    // -> 3, 6, NULL, NULL, BIGINT, [6], []
    let mut sess = session("map_basic.parquet");
    let (_, rows) = run(
        &mut sess,
        "SELECT m['a'], m['b'], m['c'], m['z'], typeof(m['b']), map_extract(m, 'b'), \
         map_extract(m, 'z'), map_extract_value(m, 'b') FROM t WHERE id = 3",
    );
    assert_eq!(
        rows[0],
        [Value::I64(3), Value::I64(6), NULL, NULL, s("BIGINT"), s("[6]"), s("[]"), Value::I64(6)]
    );
}

#[test]
fn an_integer_subscript_on_an_integer_keyed_map_is_a_key() {
    // duckdb -c "select m[0], m[1], m[2], typeof(m[1]) from 'map_int_key.parquet' where id = 0"
    // -> v0, v1, NULL, VARCHAR  (not the 1st/2nd {key,value} pair)
    let mut sess = session("map_int_key.parquet");
    let (_, rows) = run(&mut sess, "SELECT m[0], m[1], m[2], typeof(m[1]) FROM t WHERE id = 0");
    assert_eq!(rows[0], [s("v0"), s("v1"), NULL, s("VARCHAR")]);
}

// --- UNNEST ------------------------------------------------------------------------------

#[test]
fn unnest_of_a_parquet_list_column_restores_the_element_type() {
    // duckdb -c "select sum(u.x), typeof(min(u.x)) from 'list1.parquet' t, unnest(t.xs) as u(x)"
    // -> 60, INTEGER
    let mut sess = session("list1.parquet");
    let (_, rows) =
        run(&mut sess, "SELECT sum(u.x), typeof(min(u.x)) FROM t, unnest(t.xs) AS u(x)");
    assert_eq!(rows, [[Value::I128(60), s("INTEGER")]]);
    let (_, rows) = run(&mut sess, "SELECT sum(x) FROM (SELECT unnest(xs) AS x FROM t)");
    assert_eq!(rows, [[Value::I128(60)]]);
}

#[test]
fn unnest_of_string_split_and_varchar_lists_is_unquoted() {
    // duckdb -c "select unnest(string_split('a,b', ',')) || 'x'" -> ax, bx
    let mut sess = session("basic.parquet");
    let (schema, rows) =
        run(&mut sess, "SELECT unnest(string_split('a,b', ',')) || 'x' AS v FROM t WHERE id = 0");
    assert_eq!(schema[0].ty, Ty::Varchar);
    assert_eq!(rows, [[s("ax")], [s("bx")]]);
    // duckdb -c "select u.s from 'list_scalars.parquet' t, unnest(t.ss) as u(s) order by 1"
    // -> a, b"c, d\e, z
    let mut sess = session("list_scalars.parquet");
    let (_, rows) = run(&mut sess, "SELECT u.s FROM t, unnest(t.ss) AS u(s) ORDER BY 1");
    assert_eq!(rows, [[s("a")], [s("b\"c")], [s("d\\e")], [s("z")]]);
}

#[test]
fn unnest_of_non_finite_doubles_decimals_and_blobs() {
    // duckdb -c "select u.x, isnan(u.x) from 'list_scalars.parquet' t, unnest(t.ds) as u(x)
    // order by 1" -> -inf, 1.5, inf, nan (NaN sorts last)
    let mut sess = session("list_scalars.parquet");
    let (_, rows) =
        run(&mut sess, "SELECT u.x, isnan(u.x) FROM t, unnest(t.ds) AS u(x) ORDER BY 1");
    assert_eq!(rows.len(), 4);
    assert_eq!(rows[0], [Value::F64(f64::NEG_INFINITY), F]);
    assert_eq!(rows[1], [Value::F64(1.5), F]);
    assert_eq!(rows[2], [Value::F64(f64::INFINITY), F]);
    assert_eq!(rows[3][1], T);
    // duckdb -c "select sum(x) from (select unnest(decs) as x from 'list_scalars.parquet')"
    // -> 1.00
    let (_, rows) =
        run(&mut sess, "SELECT CAST(sum(x) AS VARCHAR) FROM (SELECT unnest(decs) AS x FROM t)");
    assert_eq!(rows, [[s("1.00")]]);
    // duckdb -c "select hex(b), typeof(b) from (select unnest(bs) as b from
    // 'list_scalars.parquet')" -> 0001FF, BLOB / 616263, BLOB
    let (_, rows) = run(&mut sess, "SELECT hex(b), typeof(b) FROM (SELECT unnest(bs) AS b FROM t)");
    assert_eq!(rows, [[s("0001FF"), s("BLOB")], [s("616263"), s("BLOB")]]);
    // duckdb -c "select unnest([1.0, 'nan'::DOUBLE, '-inf'::DOUBLE])" -> 1.0, nan, -inf
    let (_, rows) = run(
        &mut sess,
        "SELECT unnest([1.0, 'nan'::DOUBLE, '-inf'::DOUBLE]) AS x FROM t WHERE id = 1",
    );
    assert_eq!(rows[0], [Value::F64(1.0)]);
    assert!(matches!(rows[1][0], Value::F64(x) if x.is_nan()));
    assert_eq!(rows[2], [Value::F64(f64::NEG_INFINITY)]);
}

// --- list_contains / list_position / list_sort / list_slice -------------------------------

#[test]
fn list_contains_and_position_compare_numbers_by_value() {
    // duckdb -c "select list_contains([1.0, 2.0], 2), list_contains([1,2], 2.0),
    // list_position([1.5, 2.0], 2), list_contains(['a','b'], 'b'), list_contains([1,NULL], NULL),
    // list_position([1,NULL], NULL), list_contains([0.1::FLOAT], 0.1)"
    // -> true, true, 2, true, NULL, 2, true
    assert_eq!(
        row("list_contains([1.0, 2.0], 2), list_contains([1,2], 2.0), \
             list_position([1.5, 2.0], 2), list_contains(['a','b'], 'b'), \
             list_contains([1,NULL], NULL), list_position([1,NULL], NULL), \
             list_contains([0.1::FLOAT], 0.1)"),
        [T, T, Value::I64(2), T, NULL, Value::I64(2), T]
    );
    // DECIMAL/DOUBLE list columns against an integer needle.
    // duckdb -c "select list_position(decs, -0.5), list_contains(ds, 'inf'::DOUBLE),
    // list_contains(ss, 'b\"c') from 'list_scalars.parquet' where id = 1" -> 2, true, true
    let mut sess = session("list_scalars.parquet");
    let (_, rows) = run(
        &mut sess,
        "SELECT list_position(decs, -0.5), list_contains(ds, 'inf'::DOUBLE), \
         list_contains(ss, 'b\"c'), list_contains(ds, 1.5) FROM t WHERE id = 1",
    );
    assert_eq!(rows[0], [Value::I64(2), T, T, T]);
}

#[test]
fn list_sort_orders_like_typed_values() {
    // duckdb -c "select list_sort([3,NULL,1]), list_reverse_sort([3,NULL,1]),
    // array_sort(['b','a','B','a\"']), list_sort([[10],[9],[]]),
    // list_sort([9007199254740993, 9007199254740992]), list_sort([{'a':10},{'a':1}])"
    // -> [1, 3, NULL], [3, 1, NULL], [B, a, 'a"', b], [[], [9], [10]],
    //    [9007199254740992, 9007199254740993], [{'a': 1}, {'a': 10}]
    assert_eq!(
        row("list_sort([3,NULL,1]), list_reverse_sort([3,NULL,1]), \
             array_sort(['b','a','B','a\"']), list_sort([[10],[9],[]]), \
             list_sort([9007199254740993, 9007199254740992]), \
             list_sort(json_array(json_object('a', 10), json_object('a', 1)))"),
        [
            s("[1,3,null]"),
            s("[3,1,null]"),
            s(r#"["B","a","a\"","b"]"#),
            s("[[],[9],[10]]"),
            s("[9007199254740992,9007199254740993]"),
            s(r#"[{"a":1},{"a":10}]"#),
        ]
    );
    // duckdb -c "select list_sort([3,NULL,1], 'DESC'), list_sort([3,NULL,1], 'ASC', 'NULLS FIRST'),
    // list_reverse_sort([3,NULL,1], 'NULLS FIRST'), list_sort([3,NULL,1], 'desc', 'nulls last'),
    // array_reverse_sort([1,2])"
    // -> [3, 1, NULL], [NULL, 1, 3], [NULL, 3, 1], [3, 1, NULL], [2, 1]
    assert_eq!(
        row("list_sort([3,NULL,1], 'DESC'), list_sort([3,NULL,1], 'ASC', 'NULLS FIRST'), \
             list_reverse_sort([3,NULL,1], 'NULLS FIRST'), \
             list_sort([3,NULL,1], 'desc', 'nulls last'), array_reverse_sort([1,2])"),
        [s("[3,1,null]"), s("[null,1,3]"), s("[null,3,1]"), s("[3,1,null]"), s("[2,1]")]
    );
    // duckdb -c "select list_sort([1], 'foo')" -> an error.
    let mut sess = session("basic.parquet");
    let err = match sess.prepare("SELECT list_sort([1], 'foo') FROM t LIMIT 1", &[]) {
        Ok(Prepared::Ready(mut q)) => sess.step(&mut q).err(),
        Ok(_) => None,
        Err(e) => Some(e),
    };
    assert_eq!(code_of(err.map_or(Ok(()), Err)), Some(Code::UnsupportedFeature));
}

#[test]
fn list_slice_end_zero_is_empty() {
    // duckdb -c "select [1,2,3][0:2], [1,2,3][2:0], list_slice([1,2,3],0,0),
    // list_slice([1,2,3], 1, 0), [1,2,3][-2:0]" -> [1, 2], [], [], [], []
    assert_eq!(
        row("[1,2,3][0:2], [1,2,3][2:0], list_slice([1,2,3],0,0), list_slice([1,2,3], 1, 0), \
             [1,2,3][-2:0]"),
        [s("[1,2]"), s("[]"), s("[]"), s("[]"), s("[]")]
    );
}

// --- The JSON text of scalar leaves --------------------------------------------------------

#[test]
fn parquet_list_leaves_render_like_duckdb_to_json() {
    // duckdb -c "select to_json(ds), to_json(bs), to_json(ss), to_json(decs), to_json(dates),
    // to_json(tss), to_json(flags) from 'list_scalars.parquet' where id = 1"
    let mut sess = session("list_scalars.parquet");
    let (_, rows) =
        run(&mut sess, "SELECT ds, bs, ss, decs, dates, tss, flags FROM t WHERE id = 1");
    assert_eq!(
        rows[0],
        [
            s("[1.5,NaN,Infinity,-Infinity]"),
            s(r#"["\\x00\\x01\\xFF","abc"]"#),
            s(r#"["a","b\"c","d\\e"]"#),
            s("[1.5,-0.5]"),
            s(r#"["2024-01-02",null]"#),
            s(r#"["2024-01-02 03:04:05.5"]"#),
            s("[true,false]"),
        ]
    );
}

#[test]
fn to_json_of_non_finite_doubles_blobs_and_decimals() {
    // duckdb -c "select to_json('nan'::DOUBLE), to_json('inf'::DOUBLE), to_json('-inf'::DOUBLE),
    // to_json([1.0,'nan'::DOUBLE]), to_json('\x00\x01\xFF'::BLOB),
    // to_json(CAST('-0.50' AS DECIMAL(4,2))), to_json(100::DECIMAL(5,2)),
    // to_json(5::DECIMAL(9,0)), to_json(1.50::DECIMAL(16,2)), to_json(-0.50::DECIMAL(38,2))"
    // -> NaN, Infinity, -Infinity, [1.0,NaN], "\\x00\\x01\\xFF", -0.5, 100.0, 5.0, 1.50, -0.50
    assert_eq!(
        row("to_json('nan'::DOUBLE), to_json('inf'::DOUBLE), to_json('-inf'::DOUBLE), \
             to_json([1.0,'nan'::DOUBLE]), to_json('\\x00\\x01\\xFF'::BLOB), \
             to_json(CAST('-0.50' AS DECIMAL(4,2))), to_json(100::DECIMAL(5,2)), \
             to_json(5::DECIMAL(9,0)), to_json(1.50::DECIMAL(16,2)), \
             to_json(-0.50::DECIMAL(38,2))"),
        [
            s("NaN"),
            s("Infinity"),
            s("-Infinity"),
            s("[1.0,NaN]"),
            s(r#""\\x00\\x01\\xFF""#),
            s("-0.5"),
            s("100.0"),
            s("5.0"),
            s("1.50"),
            s("-0.50"),
        ]
    );
}

#[test]
fn json_type_classifies_integers_like_duckdb() {
    // duckdb -c "select json_type('1'), json_type('-1'), json_type('-12345678901234567890'),
    // json_type('12345678901234567890'), json_type('99999999999999999999'), json_type('-0'),
    // json_type('[NaN]', '$[0]')"
    // -> UBIGINT, BIGINT, DOUBLE, UBIGINT, DOUBLE, BIGINT, DOUBLE
    assert_eq!(
        row("json_type('1'), json_type('-1'), json_type('-12345678901234567890'), \
             json_type('12345678901234567890'), json_type('99999999999999999999'), \
             json_type('-0'), json_type('[NaN]', '$[0]')"),
        [
            s("UBIGINT"),
            s("BIGINT"),
            s("DOUBLE"),
            s("UBIGINT"),
            s("DOUBLE"),
            s("BIGINT"),
            s("DOUBLE"),
        ]
    );
}

#[test]
fn json_paths_take_duckdbs_three_forms() {
    // duckdb -c "select json_extract('{\"a\":{\"b\":1}}', '/a/b'),
    // json_extract('{\"a\":{\"b\":1}}', 'a.b'), json_extract('{\"a.b\":7}', 'a.b'),
    // json_extract('[1,[2,3]]', '/1/0'), '{\"a\":{\"b\":1}}' ->> '/a/b',
    // json_extract('{\"a\":1}', '')" -> 1, NULL, 7, 2, 1, {"a":1}
    assert_eq!(
        row(r#"json_extract('{"a":{"b":1}}', '/a/b'), json_extract('{"a":{"b":1}}', 'a.b'),
               json_extract('{"a.b":7}', 'a.b'), json_extract('[1,[2,3]]', '/1/0'),
               '{"a":{"b":1}}' ->> '/a/b', json_extract('{"a":1}', '')"#),
        [s("1"), NULL, s("7"), s("2"), s("1"), s(r#"{"a":1}"#)]
    );
}
